hangman_words = [
    {"word": "python", "hint": "A popular programming language"},
    {"word": "giraffe", "hint": "The tallest land animal"},
    {"word": "ocean", "hint": "A vast body of saltwater"},
    {"word": "guitar", "hint": "A musical instrument with strings"},
    {"word": "volcano", "hint": "A mountain that erupts lava"},
    {"word": "chocolate", "hint": "A sweet treat made from cocoa"},
    {"word": "pyramid", "hint": "An ancient Egyptian structure"},
    {"word": "basketball", "hint": "A sport played with a hoop and ball"},
    {"word": "airplane", "hint": "A flying vehicle"},
    {"word": "elephant", "hint": "A large animal with a trunk"},
    {"word": "jupiter", "hint": "The largest planet in the solar system"},
    {"word": "rainbow", "hint": "A colorful arc in the sky"},
    {"word": "hurricane", "hint": "A powerful storm with strong winds"},
    {"word": "computer", "hint": "A device used for computing tasks"},
    {"word": "penguin", "hint": "A flightless bird from Antarctica"},
    {"word": "kangaroo", "hint": "An Australian marsupial that jumps"},
    {"word": "telescope", "hint": "An instrument used to see distant objects"},
    {"word": "sandcastle", "hint": "A structure made of sand at the beach"},
    {"word": "caterpillar", "hint": "An insect that turns into a butterfly"},
    {"word": "diamond", "hint": "A precious gemstone, the hardest material"},
    {"word": "astronaut", "hint": "A person who travels in space"},
    {"word": "mountain", "hint": "A large landform that rises above the ground"},
    {"word": "notebook", "hint": "A collection of pages for writing"},
    {"word": "library", "hint": "A place filled with books"},
    {"word": "tornado", "hint": "A rapidly spinning column of air"},
    {"word": "butterfly", "hint": "An insect with colorful wings"},
    {"word": "moonlight", "hint": "Light that comes from the moon"},
    {"word": "jigsaw", "hint": "A puzzle made of interlocking pieces"},
    {"word": "fireworks", "hint": "Colorful explosions seen on celebrations"},
    {"word": "whistle", "hint": "A sound made by blowing air or a small tool"},
    {"word": "spaghetti", "hint": "A long, thin type of pasta"},
    {"word": "scarecrow", "hint": "A figure used to keep birds away from crops"},
    {"word": "compass", "hint": "A tool used to find direction"},
    {"word": "microscope", "hint": "An instrument to see tiny objects"},
    {"word": "treasure", "hint": "Hidden or valuable objects, often buried"},
    {"word": "universe", "hint": "Everything that exists, including space"},
    {"word": "octopus", "hint": "A sea creature with eight arms"},
    {"word": "sunflower", "hint": "A tall plant with a large yellow bloom"},
    {"word": "dragonfly", "hint": "A fast-flying insect with two pairs of wings"},
    {"word": "strawberry", "hint": "A small red fruit with seeds on the outside"},
    {"word": "galaxy", "hint": "A system of millions or billions of stars"},
    {"word": "lighthouse", "hint": "A tower that guides ships at sea"},
    {"word": "waterfall", "hint": "A stream of water falling from a height"},
    {"word": "backpack", "hint": "A bag carried on the back"},
    {"word": "snowflake", "hint": "A single piece of frozen ice crystal"},
    {"word": "parachute", "hint": "A device used to slow a fall from the sky"},
    {"word": "coconut", "hint": "A tropical fruit with a hard shell and white inside"},
    {"word": "boomerang", "hint": "An Australian throwing tool that returns"},
    {"word": "lantern", "hint": "A portable light source"},
    {"word": "whirlpool", "hint": "A swirling body of water"},
    {"word": "gomugomunomi", "hint": "The original name of Luffy's Devil Fruit"},
    {"word": "hitohitonomi", "hint": "Chopper's Devil Fruit that lets him talk and transform"},
    {"word": "wanokuni", "hint": "A closed-off country ruled by the Beasts Pirates"},
    {"word": "poneglyph", "hint": "Ancient stone tablets with historical secrets"},
    {"word": "pluton", "hint": "One of the Ancient Weapons, a battleship"},
    {"word": "laughtale", "hint": "The final island where One Piece is located"},
    {"word": "darkkingrayleigh", "hint": "Roger’s right-hand man and a legendary Haki user"},
    {"word": "heavenlyyaksha", "hint": "A title for Doflamingo, referencing his cruelty"},
    {"word": "Conquerorhaki", "hint": "A rare type of Haki that can knock out weak-willed opponents in English"},
    {"word": "godvalleyincident", "hint": "A legendary event where Garp and Roger fought together"},
    {"word": "worldnoble", "hint": "Descendants of the founders of the World Government"},
    {"word": "waterseven", "hint": "A city famous for its shipwrights and Aqua Laguna"},
    {"word": "thrillerbark", "hint": "A massive haunted ship ruled by Moria"},
    {"word": "skypiea", "hint": "An island in the sky where Enel ruled"},
    {"word": "gearfifth", "hint": "Luffy’s most powerful transformation"},
    {"word": "davybackfight", "hint": "A pirate game where crews can steal each other’s members"},
    {"word": "roadponeglyph", "hint": "A special red stone that leads to Laugh Tale"},
    {"word": "baratie", "hint": "The floating restaurant where Sanji used to work"},
    {"word": "reverie", "hint": "A world meeting where kings and queens gather"},
    {"word": "kozukioden", "hint": "The samurai who sailed with Roger and Whitebeard"},
    {"word": "drumisland", "hint": "The snowy island where Chopper was born"}
]
