hangman_words = [
    {"word": "luffy", "hint": "The captain of the Straw Hats who dreams of becoming Pirate King"},
    {"word": "zoro", "hint": "The swordsman who uses Three Sword Style"},
    {"word": "nami", "hint": "The navigator who draws maps and loves tangerines"},
    {"word": "usopp", "hint": "The sniper who always tells tall tales"},
    {"word": "sanji", "hint": "The cook who only fights with his legs"},
    {"word": "chopper", "hint": "The reindeer doctor who ate the Hito Hito no Mi"},
    {"word": "robin", "hint": "The archaeologist who can read Poneglyphs"},
    {"word": "franky", "hint": "The cyborg shipwright who built the Thousand Sunny"},
    {"word": "brook", "hint": "The musician of the crew, a living skeleton"},
    {"word": "jinbe", "hint": "The fishman helmsman and former Warlord of the Sea"},
    {"word": "ace", "hint": "Portgas D. Ace, Luffy's brother and user of the Mera Mera no Mi"},
    {"word": "sabo", "hint": "Luffy's other brother, Chief of Staff of the Revolutionary Army"},
    {"word": "shanks", "hint": "The red-haired Emperor who gave Luffy his straw hat"},
    {"word": "buggy", "hint": "The clown pirate who accidentally became a Warlord"},
    {"word": "mihawk", "hint": "The world's greatest swordsman who trains Zoro"},
    {"word": "crocodile", "hint": "The former Warlord who plotted to take over Alabasta"},
    {"word": "doflamingo", "hint": "The Warlord who ruled Dressrosa with his strings"},
    {"word": "enel", "hint": "The ruler of Skypiea with the Goro Goro no Mi"},
    {"word": "kaido", "hint": "The Emperor of the Beasts Pirates who ruled Wano"},
    {"word": "bigmom", "hint": "The gluttonous Emperor who rules Whole Cake Island"},
    {"word": "blackbeard", "hint": "The schemer who stole the Yami Yami no Mi"},
    {"word": "whitebeard", "hint": "The World's Strongest Man and father figure to many"},
    {"word": "roger", "hint": "The Pirate King who left the One Piece behind"},
    {"word": "oden", "hint": "The samurai of Wano who sailed with Roger and Whitebeard"},
    {"word": "yamato", "hint": "Kaido's child who idolizes Kozuki Oden"},
    {"word": "marco", "hint": "The Phoenix who was Whitebeard's right-hand man"},
    {"word": "garp", "hint": "The Hero of the Marines who raised Luffy and Ace"},
    {"word": "lucci", "hint": "The CP0 assassin with leopard powers"},
    {"word": "smoker", "hint": "The Marine who hunts Luffy with his smoke powers"},
    {"word": "kizaru", "hint": "The lazy Admiral with light-speed powers"},
    {"word": "akainu", "hint": "The ruthless Fleet Admiral with magma powers"},
    {"word": "aokiji", "hint": "The former Admiral with ice powers"},
    {"word": "fujitora", "hint": "The blind Admiral who drops meteors"},
    {"word": "monkey d luffy", "hint": "The full name of the future Pirate King"},
    {"word": "roronoa zoro", "hint": "The pirate hunter who joined the Straw Hats first"},
    {"word": "portgas d ace", "hint": "The fire-fisted son of the Pirate King"},
    {"word": "trafalgar law", "hint": "The surgeon of death from the Worst Generation"},
    {"word": "eustass kid", "hint": "The magnetic pirate captain from South Blue"},
    {"word": "jewelery bonney", "hint": "The gluttonous pirate who can change her age"},
    {"word": "tony tony chopper", "hint": "The Straw Hats' cute reindeer doctor"},
    {"word": "sir crocodile", "hint": "The sand man who was once a Warlord"},
    {"word": "gol d roger", "hint": "The true name of the Pirate King"},
    {"word": "dark king rayleigh", "hint": "Roger's right-hand man and legendary Haki master"},
    {"word": "gomu gomu nomi", "hint": "The Devil Fruit Luffy ate as a child"},
    {"word": "mera mera nomi", "hint": "The Flame-Flame Fruit used by Ace and Sabo"},
    {"word": "yami yami nomi", "hint": "The Darkness Fruit stolen by Blackbeard"},
    {"word": "goro goro nomi", "hint": "Enel's Thunder Fruit"},
    {"word": "hito hito nomi", "hint": "Chopper's Human-Human Fruit"},
    {"word": "op op nomi", "hint": "Trafalgar Law's Ope Ope no Mi"},
    {"word": "yomi yomi nomi", "hint": "Brook's Revive-Revive Fruit"},
    {"word": "uo uo nomi", "hint": "Kaido's Fish-Fish Fruit, model Azure Dragon"},
    {"word": "alabasta", "hint": "The desert kingdom of Vivi and Crocodile"},
    {"word": "skypiea", "hint": "The sky island where Enel ruled"},
    {"word": "dressrosa", "hint": "The toy kingdom ruled by Doflamingo"},
    {"word": "wano kuni", "hint": "The samurai country under Kaido's rule"},
    {"word": "sabaody", "hint": "The archipelago of bubbles and mangroves"},
    {"word": "marineford", "hint": "The Marine Headquarters where the War of the Best happened"},
    {"word": "egghead", "hint": "The future island of Dr. Vegapunk"},
    {"word": "wholecake", "hint": "Big Mom's cake-themed territory"},
    {"word": "water seven", "hint": "The city of shipwrights and Aqua Laguna"},
    {"word": "enies lobby", "hint": "The island of justice where Robin was rescued"},
    {"word": "fishman island", "hint": "The underwater island of the fishmen"},
    {"word": "drum island", "hint": "The snowy island where Chopper was born"},
    {"word": "thriller bark", "hint": "Moria's haunted ship-island"},
    {"word": "punk hazard", "hint": "The half-frozen half-burning island of Caesar"},
    {"word": "baratie", "hint": "The floating restaurant where Sanji used to work"},
    {"word": "laugh tale", "hint": "The final island where the One Piece awaits"},
    {"word": "strawhat", "hint": "The hat Shanks gave Luffy, symbol of the crew"},
    {"word": "jollyroger", "hint": "The pirate flag with a skull and crossbones"},
    {"word": "poneglyph", "hint": "Ancient stone tablets that reveal the true history"},
    {"word": "road poneglyph", "hint": "The red stones that lead to Laugh Tale"},
    {"word": "haki", "hint": "The spiritual power that can rival Devil Fruits"},
    {"word": "nakama", "hint": "The word for crewmates and friends"},
    {"word": "yonko", "hint": "The four Emperors who rule the New World"},
    {"word": "bounty", "hint": "The reward placed on a pirate's head"},
    {"word": "grandline", "hint": "The dangerous sea that leads to the One Piece"},
    {"word": "thousand sunny", "hint": "The Straw Hats' ship built by Franky"},
    {"word": "going merry", "hint": "The Straw Hats' first beloved ship"},
    {"word": "kaizoku", "hint": "The Japanese word for pirate"},
    {"word": "wanted poster", "hint": "The bounty posters of pirates"},
    {"word": "devil fruit", "hint": "The fruit that grants power but makes you sink in the sea"},
    {"word": "gear fifth", "hint": "Luffy's most powerful and goofy transformation"},
    {"word": "red line", "hint": "The mountain range that circles the globe"},
    {"word": "seastone", "hint": "The stone that nullifies Devil Fruit powers"},
    {"word": "marines", "hint": "The navy of the World Government"},
    {"word": "revolutionary army", "hint": "The army that fights the World Government"},
    {"word": "aqua laguna", "hint": "The giant wave that regularly hits Water Seven"}
];
