hangman_words = [
    {"word": "python", "hint": "A popular programming language"},
    {"word": "giraffe", "hint": "The tallest land animal"},
    {"word": "ocean", "hint": "A vast body of saltwater"},
    {"word": "guitar", "hint": "A musical instrument with strings"},
    {"word": "volcano", "hint": "A mountain that erupts lava"},
    {"word": "chocolate", "hint": "A sweet treat made from cocoa"},
    {"word": "pyramid", "hint": "An ancient Egyptian structure"},
    {"word": "basketball", "hint": "A sport played with a hoop and ball"},
    {"word": "airplane", "hint": "A flying vehicle"},
    {"word": "elephant", "hint": "A large animal with a trunk"},
    {"word": "jupiter", "hint": "The largest planet in the solar system"},
    {"word": "rainbow", "hint": "A colorful arc in the sky"},
    {"word": "hurricane", "hint": "A powerful storm with strong winds"},
    {"word": "computer", "hint": "A device used for computing tasks"},
    {"word": "penguin", "hint": "A flightless bird from Antarctica"},
    {"word": "kangaroo", "hint": "An Australian marsupial that jumps"},
    {"word": "telescope", "hint": "An instrument used to see distant objects"},
    {"word": "sandcastle", "hint": "A structure made of sand at the beach"},
    {"word": "caterpillar", "hint": "An insect that turns into a butterfly"},
    {"word": "diamond", "hint": "A precious gemstone, the hardest material"},
    {"word": "astronaut", "hint": "A person who travels in space"},
    {"word": "mountain", "hint": "A large landform that rises above the ground"},
    {"word": "notebook", "hint": "A collection of pages for writing"},
    {"word": "library", "hint": "A place filled with books"},
    {"word": "tornado", "hint": "A rapidly spinning column of air"},
    {"word": "butterfly", "hint": "An insect with colorful wings"},
    {"word": "moonlight", "hint": "Light that comes from the moon"},
    {"word": "jigsaw", "hint": "A puzzle made of interlocking pieces"},
    {"word": "fireworks", "hint": "Colorful explosions seen on celebrations"},
    {"word": "whistle", "hint": "A sound made by blowing air or a small tool"},
    {"word": "spaghetti", "hint": "A long, thin type of pasta"},
    {"word": "scarecrow", "hint": "A figure used to keep birds away from crops"},
    {"word": "compass", "hint": "A tool used to find direction"},
    {"word": "microscope", "hint": "An instrument to see tiny objects"},
    {"word": "treasure", "hint": "Hidden or valuable objects, often buried"},
    {"word": "universe", "hint": "Everything that exists, including space"},
    {"word": "octopus", "hint": "A sea creature with eight arms"},
    {"word": "sunflower", "hint": "A tall plant with a large yellow bloom"},
    {"word": "dragonfly", "hint": "A fast-flying insect with two pairs of wings"},
    {"word": "strawberry", "hint": "A small red fruit with seeds on the outside"},
    {"word": "galaxy", "hint": "A system of millions or billions of stars"},
    {"word": "lighthouse", "hint": "A tower that guides ships at sea"},
    {"word": "waterfall", "hint": "A stream of water falling from a height"},
    {"word": "backpack", "hint": "A bag carried on the back"},
    {"word": "snowflake", "hint": "A single piece of frozen ice crystal"},
    {"word": "parachute", "hint": "A device used to slow a fall from the sky"},
    {"word": "coconut", "hint": "A tropical fruit with a hard shell and white inside"},
    {"word": "boomerang", "hint": "An Australian throwing tool that returns"},
    {"word": "lantern", "hint": "A portable light source"},
    {"word": "whirlpool", "hint": "A swirling body of water"},
    {"word": "gomugomunomi", "hint": "The original name of Luffy's Devil Fruit"},

    // {"word":"apekshya   ","hint":"sani sani hissa pareki"}
]
